// styles/NotesStyles.ts

import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f1e4",
    paddingTop: 36,
    paddingBottom: 70,
  },
  title: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#6e3b3b",
    textAlign: "center",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: "#7a5c5c",
    textAlign: "center",
    marginBottom: 18,
    marginHorizontal: 20,
  },
  cardsWrapper: {
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 90,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 14,
  },
  card: {
    width: 160,
    minHeight: 120,
    backgroundColor: "#fffaf0",
    borderRadius: 18,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
    paddingVertical: 15,
    paddingHorizontal: 10,
    margin: 7,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ecd8c1",
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#6e3b3b",
    marginBottom: 5,
    textAlign: "center",
  },
  cardDetails: {
    fontSize: 14,
    color: "#7a5c5c",
    textAlign: "center",
    marginBottom: 1,
  },
  cardTag: {
    fontSize: 13,
    color: "#9e7550",
    fontStyle: "italic",
    marginTop: 3,
    textAlign: "center",
  },
  filterRow: {
  flexDirection: "row",
  alignItems: "center",
  backgroundColor: "#f6ebe2",
  borderRadius: 14,
  paddingHorizontal: 12,
  paddingVertical: 4,
  marginHorizontal: 18,
  marginBottom: 8,
  marginTop: 5,
  borderWidth: 1,
  borderColor: "#ecd8c1",
},
searchBar: {
  flex: 1,
  marginLeft: 8,
  fontSize: 15,
  color: "#6e3b3b",
  backgroundColor: "transparent",
  paddingVertical: 2,
},
filtersWrapper: {
  flexDirection: "row",
  alignItems: "center",
  marginBottom: 12,
  marginHorizontal: 10,
},
filterBtn: {
  backgroundColor: "#f4e5d6",
  borderRadius: 18,
  paddingHorizontal: 13,
  paddingVertical: 5,
  marginRight: 8,
  borderWidth: 1,
  borderColor: "#ecd8c1",
},
filterBtnActive: {
  backgroundColor: "#d2bb98",
  borderColor: "#c8a876",
},
filterText: {
  color: "#7a5c5c",
  fontSize: 14,
},
filterTextActive: {
  color: "#6e3b3b",
  fontWeight: "bold",
},
// MODAL styles
modalBg: {
  flex: 1,
  backgroundColor: "rgba(0,0,0,0.2)",
  justifyContent: "center",
  alignItems: "center",
},
modalContent: {
  backgroundColor: "#fffaf0",
  borderRadius: 18,
  width: "87%",
  padding: 22,
  elevation: 6,
  shadowColor: "#000",
  shadowOpacity: 0.18,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 5 },
},
modalTitle: {
  fontSize: 22,
  fontWeight: "bold",
  color: "#6e3b3b",
  textAlign: "center",
  marginBottom: 6,
},
modalWineName: {
  fontSize: 16,
  color: "#7a5c5c",
  fontWeight: "bold",
  textAlign: "center",
  marginBottom: 12,
},
modalLabel: {
  fontSize: 15,
  color: "#7a5c5c",
  marginBottom: 5,
  marginTop: 10,
  fontWeight: "600",
},
modalInput: {
  borderWidth: 1,
  borderColor: "#ecd8c1",
  borderRadius: 10,
  padding: 10,
  backgroundColor: "#f9f3e9",
  color: "#6e3b3b",
  fontSize: 14,
  minHeight: 40,
  maxHeight: 75,
  marginBottom: 8,
},
modalBtn: {
  backgroundColor: "#6e3b3b",
  paddingHorizontal: 22,
  paddingVertical: 8,
  borderRadius: 16,
  marginLeft: 8,
},
modalBtnText: {
  color: "#fffaf0",
  fontWeight: "bold",
  fontSize: 14,
},
modalBtnCancel: {
  backgroundColor: "#f6ebe2",
  paddingHorizontal: 18,
  paddingVertical: 8,
  borderRadius: 16,
},
modalBtnTextCancel: {
  color: "#ad9797",
  fontWeight: "bold",
  fontSize: 14,
},


});
